### ISSUE TITLE
where is your angular4-cli-boilerplate

### ISSUE THREAD

**Issue by fayeyen** [mutanttech/angular4-cli-boilerplate#1]
Can't find your angular4-cli-boilerplate only read me file.
Please

Thank you,
Yen

**Comment by mutanttech** [comment]
Hi Yen,

Thanks for dropping by and I apologize for your inconvenience. I have uploaded all the necessary files related to the boilerplate. I have also kept node_modules zipped inside the respective folder so all you need to do is to extract the zip. I would recommend you to download this repository as zip rather than clone, but you can try clone as well.  You would be required to install the Python as well. Follow the instructions from the ReadMe and let me know if you face any issues.

Cheers !
